---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink-testing
  namespace: test
  labels:
    app: sink-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sink-testing
  template:
    metadata:
      labels:
        app: sink-testing
    spec:
      containers:
      - name: sink-testing
        image: khinkali/sink-testing:todo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sink-testing
  namespace: test
spec:
  selector:
    app: sink-testing
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31400
  type: NodePort
